name: voxel-tycoon-underground CI

on:
  push:
    branches: [ "main", "develop" ] 
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      # Build da imagem Docker
      - name: Build Docker image
        run: docker build -t voxel-tycoon .

      # Rodar lint 
      - name: Run Lint
        run: docker run --rm voxel-tycoon sh -c "pip install flake8 && flake8 . --exclude=venv,env,.venv --ignore=W292"

      # # Rodar testes 
      # - name: Run Tests
      #   run: docker run --rm voxel-tycoon sh -c "pip install pytest && pytest"

      # Rodar aplicação 
      - name: Run App
        run: docker run --rm voxel-tycoon python frontend/main.py